# Generated by Django 2.0.5 on 2018-06-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180603_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bought_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
