# Generated by Django 2.0 on 2018-06-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180609_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
