# Generated by Django 2.0 on 2018-09-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, related_name='collection', to='core.Collection'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='core.Tag'),
        ),
    ]
